# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Sphinx to GitHub Pages'
description: 'GitHub Action to deploy Sphinx documentation to GitHub Pages'
author: 'Shengyu Zhang'
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  documentation_path:
    description: 'Relative path under $repository_path to documentation source files'
    required: false
    default: './docs'
  target_branch:
    description: 'Git branch where Github Pages will be deployed'
    required: false
    default: 'gh-pages'
  target_path:
    description: 'Path in Github Pages where Sphinx Pages will be placed'
    required: false
    default: '.'
  repository_path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
    default: '.'
  requirements_path:
    description: 'Relative path under $repository_path to pip requirements file'
    required: false
    default: './requirements.txt'
  sphinx_version:
    description: 'Version of Sphinx'
    required: false
    default: ''
  cache:
    description: 'Enable cache to speed up documentation building'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required by git-restore-mtime

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Restore cache
      uses: actions/cache@v3
      if: ${{ inputs.cache == 'true' }}
      with:
        path: /tmp/sphinxnotes-pages
        key: sphinxnotes-pages-${{ runner.os }}-${{ github.run_id }} # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        restore-keys: |
          sphinxnotes-pages-${{ runner.os }}

    - name: Build documentation
      run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        # See https://github.com/actions/runner/issues/665
        INPUT_DOCUMENTATION_PATH: ${{ inputs.documentation_path }}
        INPUT_TARGET_BRANCH: ${{ inputs.target_branch }}
        INPUT_TARGET_PATH: ${{ inputs.target_path }}
        INPUT_REPOSITORY_PATH: ${{ inputs.repository_path }}
        INPUT_REQUIREMENTS_PATH: ${{ inputs.requirements_path }}
        INPUT_SPHINX_VERSION: ${{ inputs.sphinx_version }}

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: /tmp/sphinxnotes-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
